[pytest]
markers =
      smoke: mark test as smoke test
      regression: mark test as regression
      functional: mark as functional
      critical: mark test as critical test
      login: test releted to login functionality
      framewwork_checks: mark test for framwork sanity
      sanity: mark test as basic sanity test

addopts =
     -ra -v

     --alluredir=report/allure-results
     --clean-alluredir
     --html=reports/html_report.html
     --self-contained-html


testpaths = test
python_files = test_*.py *_test.py
python_classes = Test* *Test
python_functions = test_*